version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory:
    steps:
      - checkout
      - restore_cache:
          keys:
            - front-npm-{{ checksum "front/package.json" }}
      - run:
          name: restore npm packages
          command: yarn
          working_directory: front
      - save_cache:
          paths:
            - front/node_modules
          key: front-npm-{{ checksum "front/package.json" }}
      - run:
          name: lint
          command: yarn lint
          working_directory: front
      - run:
          name: test
          command: yarn test:ci --code-coverage
          working_directory: front
      - run:
          name: e2e
          command: yarn e2e:ci
          working_directory: front
      - run:
          name: build
          command: yarn build --prod
          working_directory: front
      - restore_cache:
          keys:
            - functions-npm-{{ checksum "functions/package.json" }}
      - run:
          name: restore functions npm packages
          command: yarn
          working_directory: functions
      - save_cache:
          paths:
            - functions/node_modules
          key: functions-npm-{{ checksum "functions/package.json" }}
      - run:
          name: deploy
          command: yarn deploy
          working_directory: front
      - run:
          name: codecov
          command: yarn codecov
          working_directory: front
